### ISSUE TITLE
Restrict Author Categories

### ISSUE THREAD

**Issue by eddiesshop** [romulorvs/dark-mode-nitpicking-color-theme#1]
Hey there! I work at Automattic, and I want to thank you for creating this awesome plugin:
https://plugins.trac.wordpress.org/browser/restrict-author-categories/

But I write to you today, hat in hand, because my team is interested in making some internal modifications to the source code for this plugin. Specifically, we'd like to add some front end components to this file: main.6d41d871.chunk.js

But as you can imagine, working with this minified file requires a bit of extra patience.

Is there any possibility that you could share the un-minified version of this file with us?

Alternatively, since the last time you made any changes to the plugin was at least 3 years ago, would you consider publishing the source code as a GitHub repo? This would give a chance for anyone if they want to step in and start maintaining the plugin.

Or, if you don't want to go over this trouble but are wiling to share the source, I be happy to put it up on a public repo.

Hope you're having a lovely day, cheers!

**Comment by romulorvs** [comment]
Hi @eddiesshop. So `main.6d41d871.chunk.js` is basically a React build. Let me review the code and I'll get back to you.

**Comment by romulorvs** [comment]
@eddiesshop I've made available the react project for this extension at https://github.com/romulorvs/romulorvs/raw/main/reactjs.zip
Plz notice that this was my first attempt at making a WP extension, so the code is really outdated. I'm not turning the original repository public since the code there is a total mess.
Feel free to use and modify the code. Hope that can be helpful.
